#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
import json
import subprocess
import time
from pathlib import Path
from typing import Optional, Dict, List

COOKIE_FILE = "cookies.txt"
BROWSER = "chrome"  # chrome, firefox, brave, edge, opera
YT_DLP_CMD = "yt-dlp"

def get_fresh_cookies_from_browser(browser: str = BROWSER) -> bool:
    """
    Tarayıcıdan geçerli YouTube cookie'lerini çeker ve cookies.txt olarak kaydeder.
    """
    cmd = [
        YT_DLP_CMD,
        "--cookies-from-browser", browser,
        "--cookies", COOKIE_FILE,
        "--simulate",
        "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    ]
    try:
        subprocess.run(cmd, check=True, timeout=30, capture_output=True)
        print(f"[OK] {browser} üzerinden cookie'ler başarıyla çekildi.")
        return True
    except subprocess.CalledProcessError as e:
        print(f"[HATA] Tarayıcıdan cookie çekilemedi: {e.stderr.decode()}")
        return False
    except Exception as e:
        print(f"[HATA] Beklenmeyen hata: {e}")
        return False

def convert_cookies_to_netscape(cookie_dict: Dict[str, str], domain: str = ".youtube.com") -> str:
    """
    Dict formatındaki cookie'leri Netscape formatına çevirir.
    """
    lines = [
        "# Netscape HTTP Cookie File",
        "# http://curl.haxx.se/rfc/cookie_spec.html",
        "# This file was generated by palofsc cookie converter"
    ]
    for name, value in cookie_dict.items():
        lines.append(f"{domain}\tTRUE\t/\tFALSE\t0\t{name}\t{value}")
    return "\n".join(lines)

def manual_cookie_guide() -> str:
    """
    Kullanıcıya manuel cookie alma talimatlarını verir.
    """
    return (
        "MANUEL COOKIE ALMA TALİMATI:\n"
        "1. Chrome/Firefox'ta YouTube'a giriş yapın.\n"
        "2. F12 -> Application/Storage -> Cookies -> https://www.youtube.com\n"
        "3. Tüm cookie'leri (name, value) kopyalayın.\n"
        "4. Aşağıdaki formatı kullanarak 'cookies.txt' oluşturun:\n"
        ".youtube.com\tTRUE\t/\tFALSE\t0\tSESSION\tdeğer\n"
        ".youtube.com\tTRUE\t/\tFALSE\t0\tLOGIN_INFO\tdeğer\n"
        "...\n"
    )

def extract_with_deno(youtube_url: str, quality: str = "best[height<=1080][fps<=50]/best") -> Optional[str]:
    """
    Deno + ejs remote component kullanarak YouTube stream URL'sini alır.
    Bu yöntem bot korumasını aşmada daha başarılıdır.
    """
    cmd = [
        YT_DLP_CMD,
        "--no-playlist",
        "--no-warnings",
        "--user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36",
        "--referer", "https://www.youtube.com/",
        "--geo-bypass",
        "--socket-timeout", "30",
        "--cookies", COOKIE_FILE,
        "--js-runtimes", "deno",
        "--remote-components", "ejs:github",
        "--extractor-args", "youtube:player_client=default,ios,android,web",
        "-f", quality,
        "-g",
        youtube_url
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip().splitlines()[-1]  # son satır genelde stream URL
        else:
            print(f"[HATA] Deno ile alınamadı: {result.stderr[:200]}")
            return None
    except Exception as e:
        print(f"[HATA] Deno çalıştırma hatası: {e}")
        return None

def extract_classic(youtube_url: str, quality: str = "best[protocol=m3u8_native]/best[protocol=m3u8]/best") -> Optional[str]:
    """
    Klasik yt-dlp yöntemi, cookie'li ve farklı client'lerle dener.
    """
    clients = ["default", "android", "ios", "web", "tv", "mweb"]
    for client in clients:
        cmd = [
            YT_DLP_CMD,
            "--no-playlist",
            "--no-warnings",
            "--user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36",
            "--referer", "https://www.youtube.com/",
            "--geo-bypass",
            "--socket-timeout", "30",
            "--cookies", COOKIE_FILE,
            "--extractor-args", f"youtube:player_client={client}",
            "-f", quality,
            "-g",
            youtube_url
        ]
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
            if result.returncode == 0 and result.stdout.strip():
                url = result.stdout.strip().splitlines()[-1]
                if url.startswith("http"):
                    print(f"[OK] Classic client={client} ile başarılı.")
                    return url
        except Exception:
            continue
    return None

def get_stream_url_with_bypass(youtube_url: str) -> Optional[str]:
    """
    Çoklu yöntemle YouTube stream URL'sini alır.
    Önce cookie'leri yeniler, sonra Deno, sonra klasik dener.
    """
    # 1. Cookie'leri tazele
    if not Path(COOKIE_FILE).exists() or os.path.getsize(COOKIE_FILE) == 0:
        print("[INFO] Cookie dosyası yok veya boş, tarayıcıdan çekiliyor...")
        if not get_fresh_cookies_from_browser():
            print("[UYARI] Tarayıcıdan cookie çekilemedi, manuel yönlendiriliyor.")
            print(manual_cookie_guide())
            input("cookies.txt dosyasını oluşturduktan sonra ENTER tuşuna basın...")
            if not Path(COOKIE_FILE).exists():
                print("[HATA] cookies.txt hala mevcut değil, işlem iptal.")
                return None

    # 2. Deno ile dene
    print("[DENO] Deno + ejs deneniyor...")
    stream = extract_with_deno(youtube_url)
    if stream:
        return stream

    # 3. Klasik yöntem
    print("[CLASSIC] Klasik client'ler deneniyor...")
    stream = extract_classic(youtube_url)
    if stream:
        return stream

    # 4. Son çare: cookie'leri temizle ve tekrar dene
    print("[RETRY] Cookie'ler sıfırlanıyor ve yeniden deneniyor...")
    Path(COOKIE_FILE).unlink(missing_ok=True)
    if get_fresh_cookies_from_browser():
        stream = extract_classic(youtube_url)
        if stream:
            return stream
        stream = extract_with_deno(youtube_url)
        if stream:
            return stream

    print("[HATA] Tüm yöntemler başarısız oldu.")
    return None

# ----- ANA KOD ENJEKTÖRÜ -----
def patch_channel_processor(original_script_path: str):
    """
    Verilen scriptteki 'get_youtube_stream_url' fonksiyonunu bu bypass fonksiyonuyla değiştirir.
    """
    with open(original_script_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Yedek al
    backup_path = original_script_path + ".backup"
    with open(backup_path, "w", encoding="utf-8") as f:
        f.write(content)

    # Fonksiyon değişimi
    new_func = """
def get_youtube_stream_url(youtube_url: str, quality: str) -> Optional[str]:
    \"\"\"Bypass fonksiyonu - palofsc tarafından eklendi\"\"\"
    return get_stream_url_with_bypass(youtube_url)
"""
    # Eski fonksiyonu bul ve değiştir (regex veya basit replace)
    import re
    pattern = r"def get_youtube_stream_url\([^)]+\):\s*.*?(?=\ndef|\Z)"
    replacement = new_func
    new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)

    with open(original_script_path, "w", encoding="utf-8") as f:
        f.write(new_content)

    print(f"[PATCH] {original_script_path} başarıyla yamalandı. Yedek: {backup_path}")

# ----- KULLANIM -----
if __name__ == "__main__":
    # Test: Tek bir URL'yi dene
    test_url = "https://www.youtube.com/watch?v=nWsbFm6KXgQ"  # A Haber
    print(f"TEST: {test_url}")
    url = get_stream_url_with_bypass(test_url)
    if url:
        print(f"STREAM URL: {url}")
    else:
        print("STREAM ALINAMADI.")

    # Eğer ana script'in yolu verilirse yamala
    if len(sys.argv) > 1:
        patch_channel_processor(sys.argv[1])
